version: '3.7'

services:
  postgres-dev:
    container_name: postgres-dev
    image: postgres:13-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - 'POSTGRES_DB=${DATABASE_NAME}'
      - 'POSTGRES_USER=${DATABASE_USER}'
      - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD}'
    ports:
      - '${DATABASE_PORT}:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DATABASE_NAME} -U ${DATABASE_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./tmp/postgres-dev:/var/lib/postgresql/data
    networks:
      - proxy-net-dev

#  webapi-dev:
#    container_name: webapi-dev
#    restart: always
#    build:
#      context: .
#      target: backenddev
#    env_file:
#      - .env
#    ports:
#      - '${DJANGO_PORT}:${DJANGO_PORT}'
#    volumes:
#      - ./:/app
#    depends_on:
#      postgres-dev:
#        condition: service_healthy
#    networks:
#      - proxy-net-dev

networks:
  proxy-net-dev:
    name: internal_network_for_dev
