# Generated by Django 5.2.1 on 2025-05-15 14:55

import apps.ecommerce.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_content_product_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[apps.ecommerce.models.product.validate_image_size]),
        ),
    ]
