# Generated by Django 5.2.1 on 2025-05-16 15:35

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.ecommerce.models.blog
import apps.ecommerce.models.product


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0003_remove_product_image_url_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("author", models.CharField(default="Admin", max_length=100)),
                ("date", models.DateField()),
                ("image", models.ImageField(blank=True, null=True, upload_to=apps.ecommerce.models.blog.blog_image_path)),
                ("excerpt", models.TextField(blank=True, default="")),
                ("content", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
                "db_table": "ecommerce_blogs",
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=apps.ecommerce.models.product.product_image_path, validators=[apps.ecommerce.models.product.validate_image_size]),
        ),
        migrations.CreateModel(
            name="BlogImage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to=apps.ecommerce.models.blog.blog_image_path)),
                ("caption", models.CharField(blank=True, default="", max_length=200)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("blog", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="gallery", to="ecommerce.blog")),
            ],
            options={
                "verbose_name": "Blog Image",
                "verbose_name_plural": "Blog Images",
                "db_table": "ecommerce_blog_images",
                "ordering": ["display_order"],
                "abstract": False,
            },
        ),
    ]
