# Generated by Django 5.2.1 on 2025-05-21 02:41

import apps.ecommerce.models.blog
import apps.ecommerce.models.product
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_order_customer_email_order_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=apps.ecommerce.models.blog.blog_image_path),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=apps.ecommerce.models.blog.blog_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=apps.ecommerce.models.product.product_image_path, validators=[apps.ecommerce.models.product.validate_image_size]),
        ),
    ]
