# Generated by Django 5.2.1 on 2025-05-21 07:04

import apps.ecommerce.models.banner
import cloudinary_storage.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_blog_image_alter_blogimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=apps.ecommerce.models.banner.banner_image_path)),
                ('target_url', models.URLField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'ecommerce_banners',
                'ordering': ['position', '-created_at'],
                'abstract': False,
            },
        ),
    ]
