# Generated by Django 5.2.1 on 2025-06-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_remove_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number for this product', max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
